image: golang:latest

stages: 
  - test
  - build
  - package

test:
  stage: test
  script:
    - go get github.com/gofrs/uuid
    - go fmt 
    - go vet 
    - go test -race -cover
  
build:
  stage: build
  script:
    - mkdir builds
    - mkdir builds/linux
    - mkdir builds/linux/amd64
    - mkdir builds/linux/386
    - mkdir builds/linux/arm
    - mkdir builds/linux/arm64
    - go get github.com/gofrs/uuid
    - GOOS=linux GOARCH=amd64 go build $REPO_NAME -o builds/linux/amd64/failstats
    - GOOS=linux GOARCH=386 go build $REPO_NAME -o builds/linux/386/failstats
    - GOOS=linux GOARCH=arm go build $REPO_NAME -o builds/linux/arm/failstats
    - GOOS=linux GOARCH=arm64 go build $REPO_NAME -o builds/linux/arm64/failstats
  artifacts:
    when: on_success
    name: "$CI_JOB_NAME"
    paths:
      - builds

nfpm:
  stage: package
  script: 
    - git clone https://github.com/goreleaser/nfpm.git /usr/local/go/src/nfpm/
    
    - go get github.com/gofrs/uuid
    - go get github.com/Masterminds/semver/v3
	  - go get github.com/imdario/mergo
	  - go get github.com/pkg/errors
    - go get github.com/goreleaser/nfpm/glob"
	  - go get github.com/goreleaser/nfpm/internal/helpers
    - go get gopkg.in/yaml.v2

    - go get github.com/alecthomas/kingpin

    - go test nfpm
    - go build -o nfpm /usr/local/go/src/nfpm/cmd/nfpm
    - ./nfpm