image: golang:latest

before_script:
  - mkdir builds
  - mkdir builds/linux
  - mkdir builds/linux/amd64
  - mkdir builds/linux/386
  - mkdir builds/linux/arm
  - mkdir builds/linux/arm64
  - go get github.com/gofrs/uuid

stages: 
  - test
  - build
  - package

test:
  stage: test
  script:
    - go fmt 
    - go vet 
    - go test -race -cover
  
build:
  stage: build
  script:
    - GOOS=linux GOARCH=amd64 go build $REPO_NAME -o builds/linux/amd64/failstats
    - GOOS=linux GOARCH=386 go build $REPO_NAME -o builds/linux/386/failstats
    - GOOS=linux GOARCH=arm go build $REPO_NAME -o builds/linux/arm/failstats
    - GOOS=linux GOARCH=arm64 go build $REPO_NAME -o builds/linux/arm64/failstats
  artifacts:
    when: on_success
    name: "$CI_JOB_NAME"
    paths:
      - builds

nfpm:
  stage: package
  script: 
    - apt upgrade
    - apt install git
    - git clone https://github.com/goreleaser/nfpm.git nfpm
    - go test nfpm
    - go build nfpm/cmd/nfpm nfpm
    - ./nfpm