image: golang:latest

before_script:
  - mkdir builds
  - mkdir builds/linux
  - mkdir builds/linux/amd64
  - mkdir builds/linux/386
  - mkdir builds/linux/arm
  - mkdir builds/linux/arm64
  - go get github.com/gofrs/uuid

stages: 
  - test
  - build

test:
  stage: test
  script:
    - go fmt 
    - go test 
    - go vet 
    - go test --race 
  
build:
  stage: build
  script:
    - GOOS=linux GOARCH=amd64 go build $REPO_NAME -o builds/linux/amd64/failstats
    - GOOS=linux GOARCH=386 go build $REPO_NAME -o builds/linux/386/failstats
    - GOOS=linux GOARCH=arm go build $REPO_NAME -o builds/linux/arm/failstats
    - GOOS=linux GOARCH=arm64 go build $REPO_NAME -o builds/linux/arm64/failstats
  artifacts:
    when: on_success
    name: "$CI_JOB_NAME"
    paths:
      - builds