image: golang:latest

before_script:
  - mkdir -p $GOPATH/src/$REPO_NAME
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages: 
  - test
  - build

test:
  stage: test
  script:
    - go fmt
    - go test
    - go vet
    - go test --race
  
build:
  stage: build
  script:
    - go build -o failstats
  artifacts:
    when: on_success
    name: "$CI_JOB_NAME"
    paths:
      - failstats